"""init

Revision ID: 40ac011a548d
Revises: 
Create Date: 2026-05-13 17:44:33.506149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ac011a548d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('attempts', 'quiz_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('certificates', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('certificates', 'course_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('courses', 'created_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('enrollments', 'granted_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('lesson_progress', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'lesson_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('lessons', 'module_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('modules', 'course_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('quizzes', 'lesson_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('video_assets', 'lesson_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('video_assets', 'created_by',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('video_events', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('video_events', 'video_asset_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('video_progress', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('video_progress', 'video_asset_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('video_tracks', 'video_asset_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_tracks', 'video_asset_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('video_progress', 'video_asset_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('video_progress', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('video_events', 'video_asset_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('video_events', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('video_assets', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('video_assets', 'lesson_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('quizzes', 'lesson_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('modules', 'course_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('lessons', 'module_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'lesson_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('lesson_progress', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('enrollments', 'granted_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('courses', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('certificates', 'course_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('certificates', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('attempts', 'quiz_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('attempts', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
